


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #    password: "${MYSQLPASS:}"
    url: "jdbc:mysql://localhost:3306/music_gradle_security?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: 810129
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hidden-method:
      filter:
        enabled: true
  jpa:
    #    For MySQL 8
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
     hibernate:
        format_sql: true
        app:
          default:
            password: pako
     logging:
       level:
        org.springframework.security: TRACE
carousel:
    images: aerosmith.jpeg, iron.jpeg, madonna.jpg, metallica.jpg, queen.jpg, rolling.jpeg
    refresh-cron: "0 */10 * * * *"




#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/music_gradle_security?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
#    username: root
#    password: 810129
#    servlet:
#      multipart:
#        max-file-size: 1MB
#        max-request-size: 5MB
#      mvc:
#        hidden-method:
#          filter:
#            enabled: true
#
#      jpa:
#        #    For MySQL 8
#        #database-platform: org.hibernate.dialect.MySQL8Dialect
#        #For MySQL 5
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        hibernate:
#          ddl-auto: update
#        open-in-view: false
#        properties:
#          hibernate:
#            format_sql: true
#    carousel:
#      images: aerosmith.jpeg, iron.jpeg, madonna.jpg, metallica.jpg, queen.jpg, rolling.jpeg
#      refresh-cron: "0 */10 * * * *"
#
server:
  port: 6
